owner: pavelloz
repo: instances-uptimez

sites:
  - name: Sydney
    url: https://prod01.sydney.platformos.com/ping


status-website:
  # Add your custom domain below, or remove the next line if you don't have a domain
  # cname: demo.upptime.js.org
  baseUrl: /instances-uptimez
  name: Uptime
  introTitle: "platformOS status page"
  # introMessage: "Learn uptime, average response times, ongoing and past incidents"

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)